[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; Partition table: 2x OTA + NVS + SPIFFS for web portal
board_build.partitions = partitions.csv

; Build flags
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM

; Libraries
lib_deps =
    bblanchon/ArduinoJson@^7.0.0
    bogde/HX711@^0.7.5

; Monitor filters
monitor_filters = esp32_exception_decoder
